<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PawLab.Logger</RootNamespace>
    <TargetFrameworks>net472;net9.0;net8.0;net6.0;net5.0;net481;net48;</TargetFrameworks>
    <AssemblyName>PawLab.Logger</AssemblyName>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>PawLab.Logger</Title>
    <Version>1.0.1</Version>
    <Authors>xionglongztz</Authors>
    <Description>A logging system with colorful text.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/PawLaboratory/Logger</RepositoryUrl>
    <PackageTags>logger; logging; dotnet; vbnet;</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Company>PawLaboratory</Company>
  </PropertyGroup>

  <ItemGroup>
    <None Update="LICENSE.txt">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>/</PackagePath>
    </None>
  </ItemGroup>

	<ItemGroup>
		<None Include=".github\workflows\nuget.yml" />
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>
</Project>
